task :default => "shared_objects"

SRC = FileList["../source/*.f","../source/*.f90"]
OBJ = SRC.map {|s| File.basename(s)}.ext(".so")

task "shared_objects" => OBJ

SRC.each do |f|
  file File.basename(f).ext(".so") => f do |t|
    sh "wrap_all.rb -f #{f}"
  end
end
